[package]
name = "learn_rust"
version = "0.0.2"
edition = "2018"

#[dependencies]
#bigdecimal = { version="*", features = ["serde"] }

[dev-dependencies]
libc = "*"
# async runtime relative creates
actix = "*"
actix-codec = "*"
actix-web = "*"
actix-utils = "*"
futures = { version= "*", features = ["thread-pool"] }
tide = "*"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
async-std = "*"

# http client creates
reqwest = { version = "*", features = ["json"] }
awc = "*"
# openssl = "*"
hyper = "*" # support proxy
hyper-tls = "*"
# isahc = "*" # fastest? client use libcurl, support proxy, best http_client for rocket

chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"

serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
# other
regex = "*"
itertools = "*"
rand = "*"
bytes = "*"
md-5 = "*"
flate2 = "*" # gzip lib by rust-lang
