[package]
name = "rust_learn"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    # "rust_call_cpp_static_lib", # 由于macOS big sur升级带来的C++ SDK问题，所以在mac上编译不过
    "c_call_rust_lib"
]

[dev-dependencies]
libc = "*"
# async runtime relative creates
actix = "*"
actix-codec = "*"
actix-web = "*"
actix-utils = "*"
futures = { version= "*", features = ["thread-pool"] }
tide = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }
async-std = "*"

# http client creates
reqwest = { version = "*", features = ["json"] }
awc = "*"
# openssl = "*"
hyper = "*" # support proxy
# hyper-tls = "*"
# isahc = "*" # fastest? client use libcurl, support proxy, best http_client for rocket

chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"

serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
# other
#faster = "*" # easy use simd library(faster library compile failed)
lazy_static = "*"
regex = "*"
itertools = "*"
rand = "*"
bytes = "*"
md-5 = "*"
flate2 = "*" # gzip lib by rust-lang
