[package]
name = "learn_rust"
version = "0.1.1"
edition = "2021"

#[dependencies]
#bigdecimal = { version="*", features = ["serde"] }

[dev-dependencies]
# async runtime relative creates
actix = "*"
actix-web = "*"
futures = { version= "*", features = ["thread-pool"] }
tokio-uring = "0.1.0"

isahc = "*"
serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"
itertools = "*"
flate2 = "*" # gzip
rand = "*"
