[package]
name = "learn_rust"
version = "0.0.3"
edition = "2018"

#[dependencies]
#bigdecimal = { version="*", features = ["serde"] }

[dev-dependencies]
# async runtime relative creates
actix = "*"
actix-web = "*"
futures = { version= "*", features = ["thread-pool"] }
tide = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
async-std = "*"

# http client creates
hyper = "*" # support proxy
hyper-tls = "*"

serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"
itertools = "*"
md-5 = "*"
flate2 = "*" # gzip lib by rust-lang
