[package]
name = "rust_learn"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

[dev-dependencies]
actix = "*"
rand = "*"
chrono = "*"
md-5 = "*"
rust_decimal = "*" # bigdecimal-rs库的作者3个多月都没有维护了，试试另一个知名库，从sqlx更新日志得知，下个版本的sqlx支持rust-decimal
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "0.2.6"
flate2 = "*" # Rust语言主要作者alexcrichton开发的一个gzip库
tokio = { version = "*", features = ["full"] }
actix-web = "*"
actix-rt = "*"
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# dependencies for actix_web_stream_response
bytes = "*"
actix-utils = "1.0.3"

# dependencies for actix_websocket_client
awc = "*" # actix_web_client
actix-codec = "*"
futures = "*"