[package]
name = "rust_first"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
reqwest = { version = "0.10.4", features = ["json"] }
hyper = "0.13.4"
tokio = { version = "0.2.16", features = ["full"] }