[package]
name = "learn_rust"
version = "0.0.4"
edition = "2018"

#[dependencies]
#bigdecimal = { version="*", features = ["serde"] }

[dev-dependencies]
# async runtime relative creates
actix = "*"
actix-web = "*"
futures = { version= "*", features = ["thread-pool"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
async-std = "*"

isahc = "*"
serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"
itertools = "*"
flate2 = "*" # gzip lib by rust-lang
rand = "*"
