[package]
name = "rust_learn"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "rust_call_cpp_static_lib",
    "c_call_rust_lib"
]

[dev-dependencies]
libc = "*"
#nix = "*"
# async runtime relative creates
actix = "*"
actix-codec = "*"
actix-web = "*"
actix-utils = "1.0.3"
futures = "*"
tide = "*"
tokio = { version = "*", features = ["macros"] }
async-std = "*"

# http client creates
reqwest = { version = "*", features = ["json"] }
awc = "*"
# openssl = "*"
hyper = "*" # support proxy
# hyper-tls = "*"
# isahc = "*" # fastest? client use libcurl, support proxy, best http_client for rocket

chrono = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "*"

serde = { version = "*", features = ["derive"] }
serde_repr = "*"
serde_json = "*"
toml = "*"
# other
lazy_static = "*"
regex = "*"
itertools = "*"
rand = "*"
bytes = "*"
md-5 = "*"
flate2 = "*" # gzip lib by rust-lang
