[package]
name = "rust_learn"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

[workspace]
members = [
    "rust_call_cpp_static_lib",
]

[dev-dependencies]
actix = "*"
rand = "*"
chrono = "*"
md-5 = "*"
rust_decimal = "*"
bigdecimal = { version="*", features = ["serde"] }
num-bigint = "0.2.6"
flate2 = "*" # Rust语言主要作者alexcrichton开发的一个gzip库
tokio = { version = "*", features = ["full"] }
actix-web = "*"
actix-rt = "*"
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
itertools = "*"
# dependencies for actix_web_stream_response
bytes = "*"
actix-utils = "1.0.3"
# dependencies for actix_websocket_client
awc = "*" # actix_web_client
actix-codec = "*"
futures = "*"
toml = "*"