[package]
name = "rust_learn"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "*"
chrono = "*"
# 以下四个库都是在reqwest解析服务器返回的json数据中用到
tokio = { version = "*", features = ["full"] }
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

# 结论:md-5的性能最好
md-5 = "*"