[package]
name = "rust_learn"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"

[dev-dependencies]
rand = "*"
chrono = "*"
md-5 = "*"
tokio = { version = "*", features = ["full"] }
actix-web = "*"
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
