[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "hi$there"

[mysql.dbname]
production = "db_production"
#test = "db_test"

[[redis_cluster]]
url = "127.0.0.1:6379"
password = "secret"

[[redis_cluster]]
url = "8.8.8.8:6379"
